# Generated by Django 5.1.2 on 2024-10-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="subject",
            field=models.CharField(default="Без темы", max_length=200),
        ),
    ]
