# Generated by Django 5.1.2 on 2024-11-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_client_owner_message_owner_newsletter_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_block_client", "Может заблокировать клиента")],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_deactivate_newsletter", "Может деактивировать рассылку")
                ]
            },
        ),
    ]
