# Generated by Django 5.1.2 on 2024-11-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_client_options_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("can_view_client", "Может просматривать клиентов"),
                    ("can_block_client", "Может заблокировать клиента"),
                ],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_message", "Может просматривать сообщения")]
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_view_client", "Может просматривать рассылку"),
                    ("can_deactivate_newsletter", "Может деактивировать рассылку"),
                ]
            },
        ),
    ]
